name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v6
        with:
          go-version-file: .build/go.mod
          cache-dependency-path: .build/go.sum

      - run: go -C .build run .

      - uses: actions/upload-artifact@v5
        with:
          name: closure-ui
          path: |
            release/closure-ui.js
            release/closure-ui.min.js
            release/closure-ui.md
